name: Build Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: pagzoop
    env:
      GITHUB_USER: ${{ secrets.ORG_ZOOP_SDK_GITHUB_USER }}
      GITHUB_PAT: ${{ secrets.ORG_ZOOP_SDK_GITHUB_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Set gradlew executable permission
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          overwrite: false
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build
    runs-on: pagzoop

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Version from Dependency
        run: |
          VERSION=$(grep -oP 'implementation\("br\.zoop\.pos\.plugin:mpos:\K[^"]+' app/build.gradle)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: app-debug
          path: .
          merge-multiple: true

      - name: Rename Release Assets
        run: |
          if ! mv -T \
            app-debug.apk \
            app-debug-${{ env.VERSION }}.apk
          then
            echo "::error title=APK renaming::Failed to rename the APK asset to add the version suffix."
            exit 1
          fi

      - name: Launch Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          target_commitish: main
          files: app-debug-${{ env.VERSION }}.apk
          fail_on_unmatched_files: true
          prerelease: false
          draft: false
